#!/bin/sh
# Usage: filetoheader <inputfile>

# MIT License
#
# Copyright (c) 2023 Leon Marz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


INPUT="$1"

if [[ ! -f $INPUT ]]
then
	echo "$INPUT is not a file"
	exit 1
fi

NAME=$(echo $INPUT | sed 's/\./_/g')
OUTPUT="$NAME.h"
HEADER_GUARD="$NAME""_h"

echo "#ifndef $HEADER_GUARD" > $OUTPUT
echo "#define $HEADER_GUARD\n" >> $OUTPUT
echo "static const unsigned char $NAME [] = {" >> $OUTPUT
cat $INPUT | od -A n -t x1 | sed 's/\([0-9a-f]\{2\}\)/0x\1,/g' >> $OUTPUT
echo "};" >> $OUTPUT
echo "#endif /* $HEADER_GUARD */" >> $OUTPUT
